### ISSUE TITLE
universal-react-scripts in production gives an error

### ISSUE THREAD

**Issue by VegtMedia-Alex** [jamesknelson/create-react-app#3]
Hi James,

I have an error when i put the SSR in production and I really don't understand what is going on. I hope you have a few minutes for me since I really want to put the server live today.

This is the error in product, on my localhost everything runs smooth.

Uncaught SyntaxError: Unexpected token <
main.1bd1e73a.chunk.js:1 Uncaught SyntaxError: Unexpected token <

See also the screenshots attached.

I hope you can point me in the right direction.

<img width="1915" alt="Screenshot 2019-08-01 at 11 57 12" src="https://user-images.githubusercontent.com/3672692/62284451-ee037500-b453-11e9-92ed-18caed50642a.png">
<img width="1474" alt="Screenshot 2019-08-01 at 11 57 30" src="https://user-images.githubusercontent.com/3672692/62284453-ee037500-b453-11e9-9a0a-0f91d5ede96e.png">

**Comment by VegtMedia-Alex** [comment]
I have little progress i think, but now its fully crashing:

TypeError: handler is not a function
    at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:49:9)
    at /worker/worker.js:783:7
    at /worker/worker.js:766:11
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

<img width="967" alt="Screenshot 2019-08-01 at 15 23 34" src="https://user-images.githubusercontent.com/3672692/62296935-7263f100-b470-11e9-83e0-326723b07f03.png">

**Comment by jamesknelson** [comment]
Based on the first image, for whatever reason, your server is serving an error page instead of `main.something.chunk.js` - it's hard to say why. Does the file actually exist in your `build` directory?

As for "handler is not a function", that's a little more cryptic.

Do you have a URL I could take a look at?

**Comment by VegtMedia-Alex** [comment]
Let me check if I can prepare something
